import React from "react";
import {Box, Button, TextField} from "@mui/material";
import Link from "next/link";
import useAddPreYomTov from "@/server/components/use-add-pre-yom-tov";
import useAddFreeDay from "@/server/components/use-add-free-day";

const WorkdaysIsraelJourney = (props) =>{

    const [start, setStart] = React.useState(new Date().getFullYear());
    const [end, setEnd] = React.useState(new Date().getFullYear() +1);

    const [holidays, setHolidays] = React.useState([]);

    const holidaysWithErev =useAddPreYomTov(holidays) ?? [];
    // const holidaysWithErev = [...useAddPreYomTov(holidays)];

    const notWorkingDays = useAddFreeDay(holidaysWithErev, start, end);


    const firstTrying = () => {

/*

https://www.hebcal.com/hebcal?v=1&cfg=json&year=now&yt=H&maj=on&i=on&leyning=off

https://www.hebcal.com/hebcal?v=1&cfg=json&year=now&yt=H&maj=off&i=on&leyning=off&min=on

https://www.hebcal.com/hebcal?v=1&cfg=json&year=now&yt=H&maj=off&i=on&leyning=off&min=off&mod=on

for far time also work:
https://www.hebcal.com/hebcal?v=1&cfg=json&year=5950&yt=H&maj=off&i=on&leyning=off&min=off&mod=on


https://www.hebcal.com/hebcal?v=1&cfg=json&maj=on&min=on&mod=on&nx=on&year=now&month=x&ss=on&mf=on&c=on&geo=geoname&geonameid=3448439&M=on&s=on


https://www.hebcal.com/zmanim?&start=2025-01-01&end=2025-12-31&yt=H&cfg=json&im=1&geonameid=293397
 */
    }

    const calculateWorkdays = async () => {

        const response =await fetch(

            `https://www.hebcal.com/hebcal?v=1&cfg=json&start=${start}-01-01
            &end=${end}-01-01&yt=H&maj=on&i=on&yto=on&geonameid=281184      `
        );
        const data = await response.json();
        console.log("holidays = ", data);

        setHolidays(data.items);

    }










    return (<>
    <Box component="div">
        <h1>Studying on Israel Workdays API</h1>
        <h3>TODO- move it to organized locations... </h3>

        <Box>
            Credit to <Link href={"https://hebcal.com/"}>Hebcal.com </Link>: <br/>
            Content generated by the Hebcal.com web APIs is licensed under a Creative Commons Attribution 4.0 International License. This means that you can use you are free to copy and redistribute the material in any medium or format as long as you give appropriate credit to Hebcal.com.
        </Box>

        <Button onClick={firstTrying}>firstTrying</Button>


        <p>Studying this:
            https://www.hebcal.com/home/195/jewish-calendar-rest-api
        <br/>
            מגניב, בקישור כזה לדוגמא, זה מביא את כל התאריכים של השנה העכשווית העברית

            https://www.hebcal.com/hebcal?v=1&cfg=json&year=now&yt=H&maj=on&i=on

            זה כולל גם חוה"מ.
        </p>


        <Box component="div" >
            <h3>choose destination for get the holidays (Yom tov)</h3>

            <Box sx={{display: 'flex', flexDirection: 'row',
                justifyContent: 'space-between', flexWrap: 'wrap', mt:5}}>

                <Box>
                    <TextField variant={"outlined"} value = {start} label={"starting year"}


                               onChange={(e) => setStart(e.target.value)}
                    />
                </Box>

                <Box>
                    <TextField variant={"outlined"} value = {end} label={"ending year"}
                               onChange={(e) => setEnd(e.target.value)}/>
                </Box>

                <Button onClick={calculateWorkdays}
                variant={"contained"}>Generate Workdays</Button>
            </Box>


        </Box>

        <Box>
            <h3>The holidays at the picked range: </h3>
            {holidays.map((holiday) => (
                <Box component={"p"} key={holiday.date}>
                    {holiday.title} on {holiday.date}

                </Box>
            ))}
        </Box>

        <Box>
            <h3>The holidays at the picked range + Erevs: </h3>
            {holidaysWithErev.map((holiday) => (
                <Box component={"p"} key={holiday.date}>
                    {holiday.title} on {holiday.date}

                </Box>
            ))}
        </Box>

        <Box>
            <h3>All non-working days in Israel (including Atzmaut)</h3>
            {notWorkingDays.map((holiday) => (
                <Box component={"p"} key={holiday.date}>
                    {holiday.title} on {holiday.date}

                </Box>
            ))}
        </Box>
    </Box>


        </>)
}

export default WorkdaysIsraelJourney;