import React from "react";
import {Box, Button} from "@mui/material";
import Link from "next/link";

const WorkdaysIsraelJourney = (props) =>{


    const firstTrying = () => {

/*

https://www.hebcal.com/hebcal?v=1&cfg=json&year=now&yt=H&maj=on&i=on&leyning=off

https://www.hebcal.com/hebcal?v=1&cfg=json&year=now&yt=H&maj=off&i=on&leyning=off&min=on

https://www.hebcal.com/hebcal?v=1&cfg=json&year=now&yt=H&maj=off&i=on&leyning=off&min=off&mod=on

for far time also work:
https://www.hebcal.com/hebcal?v=1&cfg=json&year=5950&yt=H&maj=off&i=on&leyning=off&min=off&mod=on


https://www.hebcal.com/hebcal?v=1&cfg=json&maj=on&min=on&mod=on&nx=on&year=now&month=x&ss=on&mf=on&c=on&geo=geoname&geonameid=3448439&M=on&s=on


https://www.hebcal.com/zmanim?&start=2025-01-01&end=2025-12-31&yt=H&cfg=json&im=1&geonameid=293397
 */


    }
    return (<>
    <Box component="div">
        <h1>Studying on Israel Workdays API</h1>
        <h3>TODO- move it to organized locations... </h3>

        <Box>
            Credit to <Link href={"https://hebcal.com/"}>Hebcal.com </Link>: <br/>
            Content generated by the Hebcal.com web APIs is licensed under a Creative Commons Attribution 4.0 International License. This means that you can use you are free to copy and redistribute the material in any medium or format as long as you give appropriate credit to Hebcal.com.
        </Box>

        <Button onClick={firstTrying}>firstTrying</Button>


        <p>Studying this:
            https://www.hebcal.com/home/195/jewish-calendar-rest-api
        <br/>
            מגניב, בקישור כזה לדוגמא, זה מביא את כל התאריכים של השנה העכשווית העברית

            https://www.hebcal.com/hebcal?v=1&cfg=json&year=now&yt=H&maj=on&i=on

            זה כולל גם חוה"מ.
        </p>

    </Box>


        </>)
}

export default WorkdaysIsraelJourney;